apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: owncloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: owncloud and supporting infrastructure.
  sourceRepos:
    - https://github.com/yarsiemanym/owncloud.git
    - https://charts.bitnami.com/bitnami
  destinations:
    - namespace: owncloud
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: owncloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/yarsiemanym/owncloud.git
    targetRevision: HEAD
    path: manifests
    directory:
      exclude: argocd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: owncloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 17.17.1
    helm:
      valuesObject:
        architecture: standalone
        metrics:
          serviceMonitor:
            enabled: true
            namespace: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud-mariadb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: owncloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mariadb
    targetRevision: 13.1.1
    helm:
      valuesObject:
        auth:
          existingSecret: mariadb
          database: owncloud
          username: owncloud
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: observability
            labels:
              release: observability
  destination:
    server: "https://kubernetes.default.svc"
    namespace: owncloud
