apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: owncloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: owncloud and supporting infrastructure.
  sourceRepos:
    - https://github.com/yarsiemanym/owncloud.git
    - https://charts.bitnami.com/bitnami
  destinations:
    - namespace: owncloud
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: owncloud
  source:
    repoURL: https://github.com/yarsiemanym/owncloud.git
    targetRevision: HEAD
    path: manifests
    directory:
      include: "{namespace.yaml,secrets.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: owncloud
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 18.0.0
    helm:
      releaseName: redis
      valuesObject:
        architecture: standalone
        auth:
          enabled: false
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: owncloud
            labels:
              release: owncloud
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud-postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: owncloud
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.10.0
    helm:
      releaseName: postgresql
      valuesObject:
        architecture: standalone
        auth:
          existingSecret: postgresql
          database: owncloud
          username: owncloud
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            namespace: owncloud
            labels:
              release: owncloud
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: owncloud
  source:
    repoURL: https://github.com/yarsiemanym/owncloud.git
    targetRevision: HEAD
    path: manifests
    directory:
      exclude: "{namespace.yaml,secrets.yaml,argocd.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud