apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owncloud
  namespace: owncloud
  annotations:
    nginx.org/client-max-body-size: 512m
    nginx.org/proxy-read-timeout: "3600"
    nginx.org/proxy-send-timeout: "3600"
spec:
  tls:
    - hosts:
        - owncloud.home.saltrelli.com
      secretName: owncloud-cert
  rules:
    - host: owncloud.home.saltrelli.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: owncloud
                port: 
                  number: 80