apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: owncloud
type: Opaque
data:
  postgresqlPassword: Q2hhbmdlTWUxMjMhCg==
  replicationPassword: Q2hhbmdlTWUxMjMhCg==
  password: Q2hhbmdlTWUxMjMhCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: owncloud
  namespace: owncloud
type: Opaque
data:
  admin-password: Q2hhbmdlTWUxMjMhCg==