apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: owncloud
type: Opaque
data:
  mariadb-root-password: Q2hhbmdlTWUxMjMhCg==
  mariadb-replication-password: Q2hhbmdlTWUxMjMhCg==
  mariadb-password: Q2hhbmdlTWUxMjMhCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: owncloud
  namespace: owncloud
type: Opaque
data:
  admin-password: Q2hhbmdlTWUxMjMhCg==