apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: owncloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgresql
    namespace: owncloud
    creationPolicy:  Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: owncloud-postgresql
        property: postgres-password
    - secretKey: replication-password
      remoteRef:
        key: owncloud-postgresql
        property: replication-password
    - secretKey: password
      remoteRef:
        key: owncloud-postgresql
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: owncloud
  namespace: owncloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: owncloud
    namespace: owncloud
    creationPolicy:  Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: owncloud
        property: admin-password
