apiVersion: v1
kind: Secret
metadata:
  name: mariadb
type: Opaque
data:
  mariadb-root-password: Q2hhbmdlTWUxMjMhCg==
  mariadb-replication-password: Q2hhbmdlTWUxMjMhCg==
  mariadb-username: YWRtaW4K
  mariadb-password: Q2hhbmdlTWUxMjMhCg==
